name: Build and Test

on:
  push:
    branches: [ next, master ]
  pull_request:
    branches: [ next, master ]


jobs:
  # Build the library
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build

  # Run the test suite
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build
      - uses: cypress-io/github-action@v2
        with:
          install: false
          start: npm run test:serve
          wait-on: http://localhost:1234
          command: npm run test:cli
